/**
 * TOML configuration generation for Codex CLI profiles.
 *
 * Generates config.toml content from CodexProfile for use with CODEX_HOME.
 * MVP: MCP servers are not supported—throws if mcpServers is non-empty.
 */

import type { CodexProfile } from './schema.js';

/**
 * Generate TOML configuration content from a CodexProfile.
 *
 * @param profile - Codex profile configuration
 * @returns TOML content string for config.toml
 * @throws Error if profile has non-empty mcpServers (MVP constraint)
 */
export function generateConfigToml(profile: CodexProfile): string {
  if (Object.keys(profile.mcpServers).length > 0) {
    throw new Error('MCP servers in profiles not yet supported. Use mcpServers: {} for now.');
  }

  return (
    [
      '# Generated by vex - do not edit',
      `sandbox_mode = "${profile.sandbox}"`,
      `approval_policy = "${profile.approval}"`,
      '',
      '[features]',
      `web_search = "${profile.webSearch}"`,
      '',
      '[mcp_servers]',
      '# Empty - MCP servers disabled for vex execution',
    ].join('\n') + '\n'
  );
}
