/**
 * Tests for TOML configuration generation.
 */

import { describe, expect, test } from "bun:test";
import { BUILTIN_PROFILES } from "./schema.js";
import { generateConfigToml } from "./toml.js";

describe("generateConfigToml", () => {
  test("produces valid TOML for minimal profile", () => {
    const toml = generateConfigToml(BUILTIN_PROFILES.minimal);

    expect(toml).toContain('sandbox_mode = "read-only"');
    expect(toml).toContain('approval_policy = "on-request"');
    expect(toml).toContain('web_search = "disabled"');
    expect(toml).toContain("[mcp_servers]");
    // web_search is at top level, not under [features] - per Codex config docs
    expect(toml).not.toContain("[features]");
  });

  test("produces valid TOML for fast profile", () => {
    const toml = generateConfigToml(BUILTIN_PROFILES.fast);

    expect(toml).toContain('sandbox_mode = "workspace-write"');
    expect(toml).toContain('approval_policy = "never"');
    expect(toml).toContain('web_search = "disabled"');
  });

  test("produces valid TOML for safe profile", () => {
    const toml = generateConfigToml(BUILTIN_PROFILES.safe);

    expect(toml).toContain('sandbox_mode = "read-only"');
    expect(toml).toContain('approval_policy = "untrusted"');
    expect(toml).toContain('web_search = "cached"');
  });

  test("throws on non-empty mcpServers", () => {
    const profileWithMcp = {
      ...BUILTIN_PROFILES.minimal,
      mcpServers: { test: { command: "test" } },
    };

    expect(() => generateConfigToml(profileWithMcp)).toThrow(/MCP servers/);
  });

  test("includes generated-by comment", () => {
    const toml = generateConfigToml(BUILTIN_PROFILES.minimal);

    expect(toml).toContain("# Generated by vex");
  });
});
